Users management fixed

diff --git a/scripts/samba4u-tool b/scripts/samba4u-tool
--- a/scripts/samba4u-tool
+++ b/scripts/samba4u-tool
@@ -30,7 +30,7 @@ gid_get_name(){
 	gid_get_attr "$gid_number" "name"
 }
 gid_get_groupid(){
-	gid_number="$2"
+	gid_number="$1"
 	gid_get_attr "$gid_number" "objectSid"| sed -e "s%^.*-%%"
 }
 
@@ -79,7 +79,7 @@ objectclass: posixGroup
 add:gidnumber
 gidnumber: ${gid}
 EOF
-		ldbmodify --url=/var/lib/samba/private/sam.ldb $tmpfile || rc=$?
+		ldbmodify --url=/var/lib/samba/private/sam.ldb $tmpfile >/dev/null || rc=$?
 		rm -f "$tmpfile"
 	fi
 	return $rc
@@ -111,7 +111,8 @@ s4user_add (){
 		MAIL_OPTION="--mail-address=\"$mail_address\""
 	fi
 	rc=0
-	samba-tool user add "$user_name" --random-password --given-name="$given_name" $MAIL_OPTION --home-drive="$home_drive" 2> /dev/null || rc=$?
+	#samba-tool user add "$user_name" --random-password --given-name="$given_name" $MAIL_OPTION --home-drive="$home_drive" 2> /dev/null || rc=$?
+	samba-tool user add "$user_name" --random-password $MAIL_OPTION --home-drive="$home_drive" 2> /dev/null || rc=$?
 	if [ $rc -ne 255 ] && [ $rc -ne 0 ]; then
 		return 1
 	fi
@@ -121,18 +122,18 @@ s4user_add (){
 		gidNumber="$(user_get_attr "$user_name" "gidNumber")"
 		homeDirectory="$(user_get_attr "$user_name" "homeDirectory")"
 		employeeNumber="$(user_get_attr "$user_name" "employeeNumber")"
+		# establecer primarygroup
+		groupid="$(gid_get_groupid $gidNumber)"
 		tmpfile="$(tempfile)"
-		cat << EOF > $tmpfile
+		if [ "$uidNumber" ] ; then
+			cat << EOF > $tmpfile
 dn: cn=$user_name,$S4_USER_DN
 changetype: modify
 add:objectclass
 objectClass: posixAccount
 -
-add:objectclass
-objectClass: organizationalPerson
--
 add:uidnumber
-uiddnumber: $uidNumber
+uidnumber: $uidNumber
 -
 add:gidnumber
 gidnumber: $gidNumber
@@ -142,11 +143,20 @@ unixhomedirectory: $homeDirectory
 -
 add:loginshell
 loginshell: /bin/bash
+EOF
+#-
+#replace: primarygroupid
+#primarygroupid: $groupid
+#EOF
+			if [ "$employeeNumber" ] ; then
+				cat << EOF >> $tmpfile
 -
 add:employeeNumber
 employeeNumber: $employeeNumber
 EOF
-		ldbmodify --url=/var/lib/samba/private/sam.ldb -b $S4_BASE_DN $tmpfile || rc=2
+			fi
+		fi
+		ldbmodify --url=/var/lib/samba/private/sam.ldb -b $S4_BASE_DN $tmpfile >/dev/null || rc=2
 		rm -f "$tmpfile"
 	fi
 	[ $rc -eq 0 ] || return $rc
@@ -157,21 +167,8 @@ EOF
 	#########################################
 	[ $rc -eq 0 ] || return $rc
 
-	# establecer primarygroup
-	groupid="$(gid_get_groupid "$gidNumber")"
 
-	#set the user to the posix group
-	cat << EOF > $tmpfile
-dn: cn=$user_name,$S4_USER_DN
-changetype: modify
-replace: primarygroupid
-primarygroupid: $groupid
-EOF
-	ldbmodify --url=/var/lib/samba/private/sam.ldb -b $S4_BASE_DN $tmpfile || rc=4
-	rm -f "$tmpfile"
-	[ $rc -eq 0 ] || return $rc
-
-	samba-tool user setexpiry "$user_name" --noexpiry || rc=5
+	samba-tool user setexpiry "$user_name" --noexpiry || rc=4
 	[ $rc -eq 0 ] || return $rc
 
 	# copiamos password del ldap viejo
@@ -183,7 +180,7 @@ changetype: modify
 replace: unicodePwd
 unicodePwd:: $(/home/depinf/samba-reborn/scripts/samba4u-mkpasswd $ntpasswd) 
 EOF
-	ldbmodify --url=/var/lib/samba/private/sam.ldb --controls=local_oid:1.3.6.1.4.1.7165.4.3.12:0 -b $S4_BASE_DN $tmpfile || rc=6
+	ldbmodify --url=/var/lib/samba/private/sam.ldb --controls=local_oid:1.3.6.1.4.1.7165.4.3.12:0 -b $S4_BASE_DN $tmpfile >/dev/null || rc=6
 	rm -f "$tmpfile"
 	return $rc
 }
@@ -219,11 +216,13 @@ done
 # Add users from old ldap to s4
 user_list | while read u; do
 	if ! echo "$USERS_BLOCKED" | grep -q ":$u:" ; then
-		if s4user_add "$u" ; then
+		rc=0
+		s4user_add "$u" || rc=$?
+		if [ $rc -eq 0 ] ; then
 			echo "User $u: added"
 			echo "$u" >> $USERS_LOG
 		else
-			echo "==> ERROR adding user: $u" >&2
+			echo "==> ERROR adding user: $u ($rc)" >&2
 		fi
 	fi
 done
